<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MacBook-Air-2.local" failures="1" tests="1" name="Default test" time="1.088" errors="0" timestamp="2019-12-15T19:15:38 CST">
  <testcase classname="day63_JavaRecap.Quiz16" name="Test1" time="1.02">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method day63_JavaRecap.Quiz16.Test1() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method day63_JavaRecap.Quiz16.Test1() didn't finish within the time-out 1000
]]>
    </failure>
  </testcase> <!-- Test1 -->
</testsuite> <!-- Default test -->
